### ISSUE TITLE
Logica modelo interno (websocket, manager, ActividadDAO)

### ISSUE THREAD

**Issue by Alberto811** [danigcj31/SIGET_Equipo1#102]
Manejará toda la información relacionada con la convocatoria d elas reuniones y los usuarios involucrados

**Comment by Aharon1377** [comment]
El metodo del manager se llama convocarReunion y coge como parametros nombre de la reunion, dia, horaI, minutosI, horaF, minutosF y un JSONArray de usuarios (todo en formato String incluso el JSONArray)
