### ISSUE TITLE
Lógica modelo interno (websocket, manager, userDAO)

### ISSUE THREAD

**Issue by JorgeBaringo** [danigcj31/SIGET_Equipo1#86]

**Comment by Aharon1377** [comment]
El metodo del manager se llama eliminarUsuario y coge como parametro nombre del usuario en String

El del websocket seria parecido.

Y el metodo del manager tendria que llamar a metodo eliminar en el userDAO pudiendose realizar una comprobacion de que su rol es Asistente antes de nada
