### ISSUE TITLE
Logica interna de modificar usuario

### ISSUE THREAD

**Issue by Aharon1377** [danigcj31/SIGET_Equipo1#87]
Habría que crear un metodo mofidificar usuario en el websocket con los parametros necesarios
Y un metodo con el mismo nombre en el manager
Y otro metodo modificar en el userDAO

**Comment by danigcj31** [comment]
Los metodos que necesitabamos, son EXACTAMENTE los mismos (de momento) que los creados en la HDU11 para la modificacion de usuarios desde la vista del Admin.
