### ISSUE TITLE
En la vista usuario poder convocar reuniones

### ISSUE THREAD

**Issue by Alberto811** [danigcj31/SIGET_Equipo1#93]
El usuario tendrá una vista que le permita convocar reuniones y elegir qué usuarios estarán invitados a ella

**Comment by Aharon1377** [comment]
En la vista para cumplir el test de cucumber se deberia enviar al websocket el nombre de la reunion, el dia, horaI, minutosI, horaF, minutosF y un JSONArray de usuarios (esto en js).

En el html deberia de poder elegirse mas de un usuario.
